<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBbrQTo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBbrQTo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXBbrQTo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXBbrQTo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXBbrQTo\App_KernelDevDebugContainer([
    'container.build_hash' => 'XBbrQTo',
    'container.build_id' => 'd407dd0f',
    'container.build_time' => 1576801500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBbrQTo');
