<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDFX7J42\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDFX7J42/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDFX7J42.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDFX7J42\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDFX7J42\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DFX7J42',
    'container.build_id' => 'dd23609d',
    'container.build_time' => 1577485268,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDFX7J42');
