<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTu6i7ms\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTu6i7ms/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTu6i7ms.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTu6i7ms\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTu6i7ms\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Tu6i7ms',
    'container.build_id' => 'f64050a5',
    'container.build_time' => 1578329026,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTu6i7ms');
